services:
  deckbuilder-api:
    container_name: deckbuilder-api
    build:
      context: ./src/DeckBuilder.Api
      dockerfile: Dockerfile
    image: deckbuilder-api:latest
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
    restart: unless-stopped
